Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2021-07, with the labels that each got.

#30 Fix the windows executable file issue
  .github/workflows/publish-release.yml
  .gitignore
  build.spec
  hooks/hook-fosslight_dependency.py
  src/fosslight_dependency/analyze_dependency.py
  tox.ini
Labels: bug fix, minor

#34 Move user-guide link to FOSSLight guide & Add tox for windows
  .github/workflows/pull-request.yml
  .reuse/dep5
  README.md
  docs/user-guide.md
  docs/user-guide_Kor.md
  tests/test_cocoapods/cocoapods-tips/JWSCocoapodsTips/JWSCocoapodsTips.xcodeproj/project.pbxproj
  tests/test_cocoapods/cocoapods-tips/JWSCocoapodsTips/Podfile
  tox.ini
Labels: chore, documentation

#35 Fix the android scanning issues
  .reuse/dep5
  README.md
  setup.py
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/analyze_dependency.py
  tests/test_android/sunflower/app/android_dependency_output.txt
  tests/test_android/sunflower/app/build.gradle
  tests/test_android/sunflower/build.gradle
  tox.ini
Labels: bug fix, chore

#36 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#37 change the pypi license separator from ';' to ','
  src/fosslight_dependency/analyze_dependency.py
Labels: chore

#38 Update version in setup.py when released
  .bumpversion.cfg
  .github/workflows/publish-release.yml
  .reuse/dep5
Labels: chore
