Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2021-11, with the labels that each got.

#64 Fix url for User Guide
  README.md
Labels: documentation

#63 Add setup.py installation for pypi
  README.md
  src/fosslight_dependency/_analyze_dependency.py
  src/fosslight_dependency/_package_manager.py
  src/fosslight_dependency/constant.py
  src/fosslight_dependency/package_manager/Pypi.py
  src/fosslight_dependency/run_dependency_scanner.py
Labels: enhancement

#65 Change the log when it fails to detect the package manager
  src/fosslight_dependency/run_dependency_scanner.py
Labels: chore

#66 Fix the pypi result when pip-licenses package exists
  src/fosslight_dependency/_analyze_dependency.py
Labels: bug fix

#67 Update LicenseRef-3rd_party_licenses.txt
  LICENSES/LicenseRef-3rd_party_licenses.txt
Labels: chore

#68 Update README.md
  README.md
Labels: documentation
