Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2021-08, with the labels that each got.

#40 Merge init_log & init_log_item functiions
  .github/workflows/pull-request.yml
  src/fosslight_dependency/analyze_dependency.py
Labels: chore

#43 Set condition to use FOSSLight Util v1.1.0 or later
  requirements.txt
Labels: chore

#44 Fix the maven license result parsing issue
  src/fosslight_dependency/analyze_dependency.py
Labels: bug fix

#45 Support swift package manager
  .github/workflows/pull-request.yml
  .reuse/dep5
  README.md
  requirements.txt
  src/fosslight_dependency/analyze_dependency.py
  tests/test_swift/Package.resolved
Labels: enhancement, minor

#46 Fix a bug related release actions
  .github/workflows/publish-release.yml
Labels: bug fix

#47 Fix the gradle license parsing error
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/analyze_dependency.py
Labels: bug fix, chore

#49 Update README.md
  README.md
Labels: documentation
