Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2021-06, with the labels that each got.

#19 Add files for reuse compliance.
  .github/workflows/publish-release.yml
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  LICENSES/GPL-2.0-only.txt
  LICENSES/LicenseRef-3rd_party_licenses.txt
  README.md
  build.spec
  docs/user-guide.md
  docs/user-guide_Kor.md
  requirements-dev.txt
  src/fosslight_dependency/_version.py
  tox.ini
Labels: documentation

#20 fix the executable file import error
  src/fosslight_dependency/_version.py
  src/fosslight_dependency/analyze_dependency.py
Labels: bug fix, minor

#21 add android dependency scanning
  README.md
  docs/user-guide.md
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/_version.py
  src/fosslight_dependency/analyze_dependency.py
Labels: enhancement, minor

#22 change user guide
  docs/user-guide.md
  docs/user-guide_Kor.md
Labels: documentation

#23 Change name to FOSSLight Dependency Scanner
  README.md
  docs/user-guide_Kor.md
  setup.py
  src/fosslight_dependency/analyze_dependency.py
Labels: chore

#24 Update reuse related files
  .reuse/dep5
  LICENSES/GPL-2.0-only.txt
  README.md
  docs/user-guide.md
  docs/user-guide_Kor.md
  setup.py
Labels: documentation

#25 Update nomos standalone binary
  src/fosslight_dependency/third_party/nomos/nomossa
Labels: chore

#27 Update nomos standalone binary and source
  src/fosslight_dependency/third_party/nomos/agent/CHECKSTR
  src/fosslight_dependency/third_party/nomos/agent/GENSEARCHDATA
  src/fosslight_dependency/third_party/nomos/agent/Makefile
  src/fosslight_dependency/third_party/nomos/agent/Makefile.conf
  src/fosslight_dependency/third_party/nomos/agent/PRECHECK
  src/fosslight_dependency/third_party/nomos/agent/STRINGS.in
  src/fosslight_dependency/third_party/nomos/agent/doctorBuffer_utils.c
  src/fosslight_dependency/third_party/nomos/agent/json_writer.c
  src/fosslight_dependency/third_party/nomos/agent/json_writer.h
  src/fosslight_dependency/third_party/nomos/agent/licenses.c
  src/fosslight_dependency/third_party/nomos/agent/nomos.c
  src/fosslight_dependency/third_party/nomos/agent/nomos.h
  src/fosslight_dependency/third_party/nomos/agent/nomos_regex.c
  src/fosslight_dependency/third_party/nomos/agent/nomos_regex.h
  src/fosslight_dependency/third_party/nomos/agent/nomos_utils.c
  src/fosslight_dependency/third_party/nomos/agent/nomos_utils.h
  src/fosslight_dependency/third_party/nomos/agent/parse.c
  src/fosslight_dependency/third_party/nomos/nomossa
Labels: chore

#28 Update PR action commands
  .github/workflows/pull-request.yml
Labels: chore

#29 Fix the pub parsing error
  cli.py
  hooks/hook-fosslight_dependency.py
  setup.py
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/analyze_dependency.py
  tox.ini
Labels: bug fix, minor
