Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2022-04, with the labels that each got.

#80 Fix to show npm package license even if not spdx
  src/fosslight_dependency/package_manager/Npm.py
Labels: bug fix

#81 Add a commit message checker
  .github/workflows/pull-request.yml
Labels: chore

#82 Add a commit message checker
  .github/workflows/pull-request.yml
Labels: chore

#84 Support Package.resolved v2
  .github/workflows/pull-request.yml
  .reuse/dep5
  src/fosslight_dependency/package_manager/Swift.py
  tests/test_swift2/Package.resolved
Labels: enhancement
