Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2023-05, with the labels that each got.

#136 Support spdx format result
  requirements.txt
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/package_manager/Android.py
  src/fosslight_dependency/package_manager/Carthage.py
  src/fosslight_dependency/package_manager/Cocoapods.py
  src/fosslight_dependency/package_manager/Go.py
  src/fosslight_dependency/package_manager/Gradle.py
  src/fosslight_dependency/package_manager/Helm.py
  src/fosslight_dependency/package_manager/Maven.py
  src/fosslight_dependency/package_manager/Npm.py
  src/fosslight_dependency/package_manager/Nuget.py
  src/fosslight_dependency/package_manager/Pub.py
  src/fosslight_dependency/package_manager/Pypi.py
  src/fosslight_dependency/package_manager/Swift.py
  src/fosslight_dependency/run_dependency_scanner.py
Labels: enhancement

#137 Fix to use customized output format
  requirements.txt
  src/fosslight_dependency/run_dependency_scanner.py
Labels: bug fix

#138 Fix the github action bug
  .github/workflows/publish-release.yml
Labels: bug fix

#143 [Snyk] Upgrade console-browserify from 1.1.0 to 1.2.0
  tests/test_npm2/node_modules/jshint/package.json
Labels: chore

#144 [Snyk] Upgrade punycode from 2.1.0 to 2.3.0
  tests/test_npm2/node_modules/uri-js/package.json
  tests/test_npm2/node_modules/uri-js/yarn.lock
Labels: chore

#142 [Snyk] Upgrade minimatch from 3.0.8 to 3.1.2
  tests/test_npm2/node_modules/jshint/package.json
Labels: chore

#145 [Snyk] Upgrade negotiator from 0.6.2 to 0.6.3
  tests/test_npm2/node_modules/accepts/package.json
Labels: chore

#139 Change None string to N/A for pub homepage
  src/fosslight_dependency/package_manager/Pub.py
Labels: chore
