Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2024-10, with the labels that each got.

#225 Refactor existing tox test to pytest
  requirements-dev.txt
  requirements.txt
  tests/pytest/conftest.py
  tests/pytest/package_manager/__init__.py
  tests/pytest/package_manager/test_android.py
  tests/pytest/package_manager/test_cocoapods.py
  tests/pytest/package_manager/test_gradle.py
  tests/pytest/package_manager/test_helm.py
  tests/pytest/package_manager/test_maven.py
  tests/pytest/package_manager/test_npm.py
  tests/pytest/package_manager/test_nuget.py
  tests/pytest/package_manager/test_pub.py
  tests/pytest/package_manager/test_pypi.py
  tox.ini
Labels: chore

#226 Update spdx function
  requirements.txt
  src/fosslight_dependency/run_dependency_scanner.py
Labels: chore, minor

#227 Support swift package.resolved v3
  src/fosslight_dependency/_package_manager.py
  src/fosslight_dependency/package_manager/Swift.py
Labels: chore

#230 Support cargo package manager
  .reuse/dep5
  README.md
  src/fosslight_dependency/_analyze_dependency.py
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/_package_manager.py
  src/fosslight_dependency/constant.py
  src/fosslight_dependency/package_manager/Cargo.py
  tests/pytest/conftest.py
  tests/pytest/package_manager/test_cargo.py
  tests/test_cargo/Cargo.toml
  tests/test_cargo/tmp_cargo_fosslight_output.json
Labels: enhancement
