Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2024-08, with the labels that each got.

#215 Fix the macos npm github action bug
  .github/workflows/pull-request.yml
Labels: bug fix

#214 Add feature that save graph image
  requirements.txt
  src/fosslight_dependency/_graph_convertor.py
  src/fosslight_dependency/_help.py
  src/fosslight_dependency/run_dependency_scanner.py
Labels: enhancement

#216 Add dummy in github action token
  .github/workflows/pull-request.yml
Labels: chore

#217 Modify homepage to empty if it is external repo
  src/fosslight_dependency/package_manager/Cocoapods.py
Labels: chore

#223 Limit installation to fosslight_util 1.4.*
  requirements.txt
Labels: chore
