Repository fosslight/fosslight_dependency_scanner, pull requests merged in 2024-01, with the labels that each got.

#185 Fix the npm issue (no dependencies in package.json)
  src/fosslight_dependency/package_manager/Npm.py
Labels: bug fix

#186 Add exception when no dependencies in Chart.yaml
  src/fosslight_dependency/package_manager/Helm.py
Labels: bug fix

#187 Fix the pypi direct/transitive bug, Support pyproject.toml
  src/fosslight_dependency/constant.py
  src/fosslight_dependency/package_manager/Pypi.py
Labels: enhancement, bug fix, minor

#188 Use common github actions
  .github/workflows/pull-request.yml
Labels: chore
